name: Run tagpr

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tagpr:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - run: go install github.com/snaka/tagpr/cmd/tagpr@debug-20240919-1708
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.TAGPR_APP_ID }}
          private-key: ${{ secrets.TAGPR_PRIVATE_KEY }}
      - run: tagpr
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
