name: Run tagpr

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tagpr:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: snaka/tagpr@debug-20240919-1613
        with:
          version: "debug-20240919-1613"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
